# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Simple History
tagline:          'A site and user activity feed plugin for WordPress'
description:      'Site and user activity feed<br>plugin for WordPress'
url:              https://wordpress.org/plugins/simple-history/

author:
  name:           'Pär Thernström'
  url:            https://twitter.com/eskapism

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/bonny/WordPress-Simple-History
